### ISSUE TITLE
Handling new menu object

### ISSUE THREAD

**Issue by mhowe0422** [CodeForPittsburgh/fishfrymap#15]
Working on the adding updated code

**Comment by mhowe0422** [comment]
I have a test version running.

**Comment by mhowe0422** [comment]
Pittsburgh Moose has a Long URL. Need to wrap within the space

**Comment by gassc** [comment]
Let's hide menu (and venue) URLs behind an anchor element.

**Comment by gassc** [comment]
https://github.com/CodeForPittsburgh/fishfrymap/issues/6
