### ISSUE TITLE
Year title changes

### ISSUE THREAD

**Issue by mhowe0422** [CodeForPittsburgh/fishfrymap#30]
Any year references in titles/text should be changed to reflect the current year. This will prevent annual edits.

**Comment by mhowe0422** [comment]
I found in my copy of app.js line 439 Notify has 2018 in the string. This will need a current year function.

**Comment by gassc** [comment]
re:
>  "found in my copy of app.js line 439 Notify has 2018 in the string"

Addressed with https://github.com/CodeForPittsburgh/fishfrymap/commit/e4fef03ed148ca644ab8d3b9ff6442612bf65cd2
