### ISSUE TITLE
Good Friday test

### ISSUE THREAD

**Issue by mhowe0422** [CodeForPittsburgh/fishfrymap#31]
Working on updating bulk start/end dates, I found that the code for Good Friday open/closed will need changed. It would be better to have a calculation for Good Friday instead of a program constant.
Easter -2 days as a start. php has a function easter_date(year) which returns the date.
function dateGoodFriday($EasterYear, $daysback) {
    $easter = getDate(easter_date($EasterYear));
    return mktime(0, 0, 0, $easter['mon'], $easter['mday'] - $daysback, $easter['year']);
}
leapyear has to be considered in any long range date calculation.

**Comment by gassc** [comment]
I agree--not having that hardcoded is the way to go. I'm sure we can find something similar to that `php` function in a `JS` library for the front-end. I know there is a Python library that does something similar if we for whatever reason wanted to have that logic to the back end (fishfryform)

**Comment by mhowe0422** [comment]
I found in app.js lines 321 and 765 (at least in my copy) the reference test for Good Friday Date

**Comment by mhowe0422** [comment]
This will need the Good Friday date calculation (could be Easter - 2) for the test date

**Comment by gassc** [comment]
Would this work? https://stackoverflow.com/questions/1284314/easter-date-in-javascript#1284335

**Comment by mhowe0422** [comment]
not as simple as the php easter_date($year). I'll check it out

**Comment by gassc** [comment]
@mhowe0422 tes, unfortunately the JS standard library not as full featured. I can add this code in if you'd like to replace the hard-coded Easter variables.

**Comment by mhowe0422** [comment]
Yep, if you create the function, I'll change the code for Good Friday

**Comment by gassc** [comment]
@mhowe0422 here's what I've got queued up using the function I linked to above:
```javascript
// thisYear = 2019;
thisYear = moment().year();
easterThisYear = moment(Easter(thisYear));
goodFridayThisYear = easterThisYear.subtract(2, 'd');
```
Do you want it to always auto-detect the current year? The code above does that. Or do we need to a least indicate what year we're on (somewhere; e.g., with a hardcoded `thisYear` constant as shown commented-out above).

**Comment by mhowe0422** [comment]
This is exactly what should be added; with the auto-detect current year.

**Comment by gassc** [comment]
Addressed with https://github.com/CodeForPittsburgh/fishfrymap/commit/e4fef03ed148ca644ab8d3b9ff6442612bf65cd2
