### ISSUE TITLE
index.html title page

### ISSUE THREAD

**Issue by mhowe0422** [CodeForPittsburgh/fishfrymap#32]
Maybe just drop the year?
<title>2018 Pittsburgh Lenten Fish Fry Map</title>
                <a class="navbar-brand hidden-xs hidden-sm" href="#">2018 Pittsburgh Lenten Fish Fry Map</a>
                <a class="navbar-brand hidden-md hidden-lg small" href="#">2018 Fish Fry Map</a>
<input class="filter" id='publish' type="checkbox">Show only those verified for 2018.
or code for current year

**Comment by mhowe0422** [comment]
just changed all 2018 to 2019

**Comment by gassc** [comment]
Awesome, thanks Mark!
