### ISSUE TITLE
Location for Aspinwall Catholic church is wrong on the map

### ISSUE THREAD

**Issue by rickined** [CodeForPittsburgh/fishfrymap#36]
The info is correct re the address but the map pin is in the middle of O'Hara township.

**Comment by mhowe0422** [comment]
I'm not showing an entry for Aspinwall Catholic Church, what is the listed name and address

Thanks

________________________________
From: rickined ***@***.***>
Sent: Thursday, February 23, 2023 8:37 AM
To: CodeForPittsburgh/fishfrymap ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [CodeForPittsburgh/fishfrymap] Location for Aspinwall Catholic church is wrong on the map (Issue #36)


The info is correct re the address but the map pin is in the middle of O'Hara township.

**Comment by rickined** [comment]
Christ the Divine Teacher Academy
Church
205 Brilliant Avenue Aspinwall, PA 15215

**Comment by mhowe0422** [comment]
Pin location has been corrected.

Thanks

________________________________

**Comment by mhowe0422** [comment]
Reset address and map pin location was corrected
