### ISSUE TITLE
Please add this fish fry

### ISSUE THREAD

**Issue by andrewzigerelli** [CodeForPittsburgh/fishfrymap#4]
Economy Volunteer Fire Department
3308 Conway Wallrose Rd
4pm-7pm
For takeout, call ahead so you wait less time
724-266-3714 or 724-266-1116

I'm a member of this VFD. I just got done with prep work.

Every Friday during lent.

I will attach an updated menu with prices( which I will have by next week).

Fish, Crab Cakes, Fried Shrimp, Chicken, Coleslaw, Mac n Cheese, French Fries,

**Comment by gassc** [comment]
@andrewzigerelli done! Your VFD will appear on the map in a bit. 

You're the first to submit a Fish Fry request on GitHub 🥇

**Comment by andrewzigerelli** [comment]
Thank you so much! It is very much appreciated.

Here is the updated menu. https://u.nya.is/wwqytt.jpg. Hopefully that link stays up.

Also, regarding the questions:
No pierogies.
Alcohol served: beer and wine.
No lunch.

Handicap accessible: Please let parking lot attendants know and they will park you in the handicap location.

Type of venue: social hall.

1 more issue:
We have three addresses (for 3 stations in our department). Is it possible to put the address above on the map?
On openmap, this query: http://www.openstreetmap.org/search?query=economy%20fire%20department#map=12/40.6326/-80.1607

The location of the fish fry is "Economy Volunteer Fire Department 1 Station 69" on the link above.

Again, thanks so much!

**Comment by gassc** [comment]
Done!

**Comment by andrewzigerelli** [comment]
Thanks Christian!
